# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               nonplus
tagline:             '.me'
description:         'a blog'
url:                 http://nonplus.me
baseurl:             'http://nonplus.me'
paginate:            5

# About/contact
author:
  name:              scotts
  url:               https://twitter.com/sortedaffairs
  email:             scott@nonplus.me

# Custom vars
version:             1.0.0
